### ISSUE TITLE
Markdown formatting

### ISSUE THREAD

**Issue by germede** [PramitKumar27/djlokal#1]
Hello,

the README.md file you provided as client is formatted as simply plain text.

Is it okay for you, if we adapt the README.md with Markdown titles, tables, list, etc. for a better readability?

This issue means still no content adaptation but purely formatting improvements. 

Thank you in advance.

**Comment by ruehsflo** [comment]
It is ok if you adapt the formatting

**Comment by germede** [comment]
Thanks :)
