### ISSUE TITLE
No user roles

### ISSUE THREAD

**Issue by germede** [PramitKumar27/djlokal#5]
As far as I can see from the business requirements, 
no user roles are being defined so every registered user is able to:
- Manage (show, create, **update**, **delete**) all events, locations and DJs.
- Enter and see feedback to all of them.
- See "Best-of" overviews. 

Is this, in the context of this course and our development capabilities, intentional and correct?

**Comment by ruehsflo** [comment]
Since we did not learn about authorization or authentification it is intended that no user roles exists yet

**Comment by germede** [comment]
thank you !
