### ISSUE TITLE
Feedback fields

### ISSUE THREAD

**Issue by germede** [PramitKumar27/djlokal#8]
What is a feedback made of? 
If it's a simple text comment, how should be evaluated, which events, locations, dj's are the "best"?

**Comment by ruehsflo** [comment]
A feedback should consist of a text comment and a rating, like 1-5 stars or 1-10 points or whatever, you can decide that. Maybe its good to have an average rating to rank events, locations and dj's

**Comment by germede** [comment]
Okay thank you!
