### ISSUE TITLE
ID generation and usage

### ISSUE THREAD

**Issue by uniChkhitunidze** [PramitKumar27/djlokal#9]
How are the IDs for events, locations and DJs generated? Are they assigned automatically or does the system expect users to enter them?
If the IDs are generated automatically, are there specific rules or patterns by which they are created?
Are the IDs unique and do they serve as unique identifiers for each entry?
Are the IDs for events, locations, and DJs displayed in the user interface or are they internal references used only in the background?

**Comment by ruehsflo** [comment]
IDs are unique and should be displayed. I think its good if they are generated like the first entry gets id 0 and then for every following entry this is incremented if you know what I mean

**Comment by uniChkhitunidze** [comment]
thank you
